trigger:
  branches:
    include:
      - main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'  # Update to match your Angular version compatibility

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

- script: |
    ng build --configuration production
  displayName: 'Build Angular App'

# Optional: Run tests
- script: |
    ng test --watch=false --browsers=ChromeHeadless
  displayName: 'Run Unit Tests'

# Optional: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'angular-app'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
